### ISSUE TITLE
centos和OS X都出现这个

### ISSUE THREAD

**Issue by y500** [houtianze/bypy#212]
[root@iZ28p64twbgZ ~]# bypy info -dv
Loading Hash Cache File '/root/.bypy/bypy.hashcache.json'...
Hash Cache File '/root/.bypy/bypy.hashcache.json' not found, no caching
----
Verbose level = 1
Debug level = 1
Config direcotry: '/root/.bypy'
Token file: '/root/.bypy/bypy.json'
Hash Cache file: '/root/.bypy/bypy.hashcache.json'
App root path at Baidu Yun '/apps/bypy'
sys.stdin.encoding = UTF-8
sys.stdout.encoding = UTF-8
sys.stderr.encoding = UTF-8
----

<E> [16:11:57] Exception occurred:
Exception:
<type 'exceptions.AttributeError'> - 'unicode' object has no attribute 'formatex'
Stack:  File "/usr/bin/bypy.py", line 3999, in <module>
    main()
  File "/usr/bin/bypy.py", line 3992, in main
    perr("Exception occurred:\n{}".format(formatex(ex)))
  File "/usr/bin/bypy.py", line 433, in formatex
    type(ex), ex, ''.join(traceback.format_stack()))

Abort
Skip saving Hash Cache since it has not been updated.

根据之前的issue改了systemencoding还是不行。

**Comment by tcz717** [comment]
Loading Hash Cache File '/home/tcz/.bypy/bypy.hashcache.json'...
Hash Cache File '/home/tcz/.bypy/bypy.hashcache.json' not found, no caching

Verbose level = 1
Debug level = 1
Config direcotry: '/home/tcz/.bypy'
Token file: '/home/tcz/.bypy/bypy.json'
Hash Cache file: '/home/tcz/.bypy/bypy.hashcache.json'
App root path at Baidu Yun '/apps/bypy'
sys.stdin.encoding = UTF-8
sys.stdout.encoding = UTF-8
sys.stderr.encoding = UTF-8

<E> [17:01:15] Exception occurred:
Exception:
<class 'AttributeError'> - 'str' object has no attribute 'formatex'
Stack:  File "./bypy.py", line 4015, in <module>
    main()
  File "./bypy.py", line 4008, in main
    perr("Exception occurred:\n{}".format(formatex(ex)))
  File "./bypy.py", line 433, in formatex
    type(ex), ex, ''.join(traceback.format_stack()))

Abort
Skip saving Hash Cache since it has not been updated.

我也出现了这样的问题

**Comment by houtianze** [comment]
感谢反馈。

犯了一个低级语法错误，最新版应该已经修正。

**Comment by tcz717** [comment]
似乎没有完全修正 还是有错误提示

Verbose level = 1
Debug level = 1
Config direcotry: '/home/tcz/.bypy'
Token file: '/home/tcz/.bypy/bypy.json'
Hash Cache file: '/home/tcz/.bypy/bypy.hashcache.json'
App root path at Baidu Yun '/apps/bypy'
sys.stdin.encoding = UTF-8
sys.stdout.encoding = UTF-8
sys.stderr.encoding = UTF-8

<E> [19:04:16] Error while loading baidu pcs token.
Exception:
<class 'FileNotFoundError'> - [Errno 2] No such file or directory: '/home/tcz/.bypy/bypy.json'
Stack:  File "/usr/bin/bypy.py", line 4016, in <module>
    main()
  File "/usr/bin/bypy.py", line 3988, in main
    verbose = args.verbose, debug = args.debug)
  File "/usr/bin/bypy.py", line 1464, in __init__
    if not self.__load_local_json():
  File "/usr/bin/bypy.py", line 1809, in __load_local_json
    perr("Error while loading baidu pcs token.\n{}".format(formatex(ex)))
  File "/usr/bin/bypy.py", line 433, in formatex
    type(ex), ex, ''.join(traceback.format_stack()))

**Comment by houtianze** [comment]
感谢再次反馈。
这个有点怪，是不是第一次运行，还没有授权？
授权后第二次跑就没这个错误提示了吧？

**Comment by tcz717** [comment]
是的 再次运行就没有了

**Comment by houtianze** [comment]
哦，那时正常。不过那个错误的显示是有点误导，改成用调试输出形式了。

**Comment by y500** [comment]
修改之后就好了：）
