### ISSUE TITLE
Automatically resume downloading?

### ISSUE THREAD

**Issue by panCtrlV** [houtianze/bypy#264]
Occasionally, my `bypy downdir` reports the following error message:

```bash
[=======_____________] 35% (480.0MB/1.3GB) ETA: 3h22m (73kB/s, 1h52m gone) <E> [10:56:13] Waiting 10 seconds before retrying...
<E> [10:56:23] Request Try #2 / 5
<E> [10:57:55] Waiting 20 seconds before retrying...
<E> [10:58:15] Request Try #3 / 5
<E> [11:00:13] Waiting 30 seconds before retrying...
<E> [11:00:43] Request Try #4 / 5
<E> [11:02:56] Waiting 40 seconds before retrying...
<E> [11:03:36] Request Try #5 / 5
<E> [11:07:24] Maximum number (5) of tries failed.
```

and then it quits downloading. I want to know if it is possible to let `bypy downdir` resume the downloading automatically. Is there any option which servers this purpose? 

This is because I want to start downloading on my Banana Pro and then leave. It would be very frustrating to see that my downloading is stopped at 35% when I come back home.

If possible, could you let me know what is the reason for this issue to happen?

Thanks,
Pan

**Comment by houtianze** [comment]
You are downloading one file only? This happens when there are some network connection issues and bypy can't connect after 5 failed attempts. You can use arguments `-dv` to get more info on what happened.

The default retry count is 5, and if you are sure this is due to intermittent network connection, you can increase this with the `-r <count>` parameter, for example, `-r 100` will retry 100 time before the program gives up and quits.
