### ISSUE TITLE
Multi-Process syncdown Error

### ISSUE THREAD

**Issue by rexx6** [houtianze/bypy#358]
Hello.. 

I updated to V.1.5.0 and used multiprocess function. But I got below error message.

```
root@all4u:~# bypy --processes 2 syncdown
<W> [10:45:22] Running multiple (2) processes for Sync down, I don't know if things will go awry...
<E> [10:45:23] Exception occurred:
Exception:
<class 'cPickle.PicklingError'> - Can't pickle <type 'instancemethod'>: attribute lookup __builtin__.instancemethod failed
Stack:
  File "/usr/local/bin/bypy", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/bypy/bypy.py", line 3525, in main
    perr("Exception occurred:\n{}".format(formatex(ex)))
  File "/usr/local/lib/python2.7/dist-packages/bypy/util.py", line 73, in formatex
    type(ex), ex, ''.join(traceback.format_stack()))

Abort
Traceback (most recent call last):
  File "/usr/local/bin/bypy", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/bypy/bypy.py", line 3511, in main
    result = getattr(by, args.command[0])(*uargs)
  File "/usr/local/lib/python2.7/dist-packages/bypy/bypy.py", line 2613, in syncdown
    subresult = self.__syncdown_multi(rpath, localdir, compare_result)
  File "/usr/local/lib/python2.7/dist-packages/bypy/bypy.py", line 2591, in __syncdown_multi
    subresult = self.__multi_process(worker, diff, "Sync down")
  File "/usr/local/lib/python2.7/dist-packages/bypy/bypy.py", line 504, in __multi_process
    results = ar.get(const.TenYearInSeconds)
  File "/usr/local/lib/python2.7/dist-packages/multiprocess/pool.py", line 567, in get
    raise self._value
cPickle.PicklingError: Can't pickle <type 'instancemethod'>: attribute lookup __builtin__.instancemethod failed
Signal 15 received, Abort
```

Below is installed package and version on my system.
```
root@all4u:~# pip list -v --format=columns
Package           Version
----------------- -------
appdirs           1.4.3  
attrs             15.2.0 
bypy              1.5.0  
chardet           2.3.0  
cryptography      1.2.3  
deluge            1.3.14 
dill              0.2.6  
dnspython         1.12.0 
enum34            1.1.2  
get               0.0.0  
idna              2.0    
ipaddress         1.0.16 
multiprocess      0.70.5 
packaging         16.8   
Pillow            3.1.2  
pip               9.0.1  
post              0.0.0  
public            0.0.0  
pyasn1            0.1.9  
pyasn1-modules    0.0.7  
pycrypto          2.6.1  
pyOpenSSL         0.15.1 
pyparsing         2.2.0  
python-apt        1.1.0b1
python-libtorrent 1.0.11 
pyxdg             0.25   
query-string      0.0.0  
request           0.0.0  
requests          2.14.1 
service-identity  16.0.0 
setupfiles        0.0.0  
setuptools        35.0.2 
six               1.10.0 
Twisted           16.0.0 
zope.interface    4.1.3  
```

Sincerely yours.

**Comment by houtianze** [comment]
Thanks for feeding back.

The problem does seem very weird:
- I have the same versions of `multiprocess` and `dill` installed for Python 2.7.x, but I don't have this error syncing / dl / ul directories.
- I know exactly how this error would occur - if I use Pythons's builtin `multiprocessing` library instead of the fixed 3rd party library `multiprocess`.

So my suspicion is that the `multiprocess` library may not have been built / installed successfully. Can you please try the following 2 python snippet to see if both of them throw errors?
```python
from multiprocessing import Pool

class C:
    def foo(self, s):
        print(s)

if __name__ == "__main__":
    pool = Pool()
    o = C()
    ar = pool.map_async(o.foo, range(4))
    print(ar.get())
```

```python
from multiprocess import Pool

class C:
    def foo(self, s):
        print(s)

if __name__ == "__main__":
    pool = Pool()
    o = C()
    ar = pool.map_async(o.foo, range(4))
    print(ar.get())
```

The correct behavior would be the first one throws the same error you posted, but the second one should run without problem.

If both snippets give errors on your system, then I suspect `dill` or `multiprocess` has not been correctly installed. You can try if uninstalling and re-installing them will solve the problem (sudo maybe needed for the following commands)
```
pip uninstall multiprocess
pip uninstall dill
pip install multiprocess
```
Observe if there are any errors during the multiprocess installation (It requires a C compiler to compile some C code, if you notice something like "WARNING: The C extensions could not be compiled" in the console, then I think `multiprocess` is not going to be installed correctly).

Grunt: All the hassles should have been saved if Python has done `multiprocessing` correctly in the first place (What's even sadder is that they don't seem going to fix this, `pickle` sucks)

**Comment by rexx6** [comment]
Hi..

During the installation of the multiprocess with -v option, the "WARNING: The C extensions..." message was found. 

I installed C compiler, python-dev, etc. And reinstalled multiprocess.

At present, It works very well.

Thank you for your support.
