### ISSUE TITLE
Failed to save hash cache due to unicode error

### ISSUE THREAD

**Issue by d3banjan** [houtianze/bypy#437]
> ```
> Saving Hash Cache...
> <E> [21:16:17] Failed to save Hash Cache.
> Exception:
> <type 'exceptions.UnicodeDecodeError'> - 'ascii' codec can't decode byte 0xe2 in position 22: ordinal not in range(128)
> Stack:
>   File "/usr/lib/python2.7/threading.py", line 774, in __bootstrap
>     self.__bootstrap_inner()
>   File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
>     self.run()
>   File "/usr/lib/python2.7/threading.py", line 754, in run
>     self.__target(*self.__args, **self.__kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/bypy/gui.py", line 300, in syncupproc
>     self.byp.syncup(lpath, rpath, delete)
>   File "/usr/local/lib/python2.7/dist-packages/bypy/bypy.py", line 2882, in syncup
>     compare_result = self.__compare(rpath, localdir, True)
>   File "/usr/local/lib/python2.7/dist-packages/bypy/bypy.py", line 2574, in __compare
>     self.__gather_local_dir(localdir)
>   File "/usr/local/lib/python2.7/dist-packages/bypy/bypy.py", line 2544, in __gather_local_dir
>     self.__proceed_local_gather(len(dir), walk)
>   File "/usr/local/lib/python2.7/dist-packages/bypy/bypy.py", line 2529, in __proceed_local_gather
>     files.append((name, getfilesize(fullname), md5(fullname)))
>   File "/usr/local/lib/python2.7/dist-packages/bypy/cached.py", line 96, in __call__
>     self.__store(info, path, result)
>   File "/usr/local/lib/python2.7/dist-packages/bypy/cached.py", line 124, in __store
>     cached.savecache()
>   File "/usr/local/lib/python2.7/dist-packages/bypy/cached.py", line 226, in savecache
>     perr("Failed to save Hash Cache.\n{}".format(formatex(ex)))
>   File "/usr/local/lib/python2.7/dist-packages/bypy/util.py", line 73, in formatex
>     type(ex), ex, ''.join(traceback.format_stack()))
> ```

my system is a gnome install of ubuntu 17.10

**Comment by d3banjan** [comment]
Using only bypy, the error message is simpler. 

```
$ bypy ls 
<E> [13:36:24] Fail to load the Hash Cache, no caching.
Exception:
<type 'exceptions.ValueError'> - No JSON object could be decoded
Stack:
  File "/usr/local/bin/bypy", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/bypy/bypy.py", line 3663, in main
    by = ByPy(**bypyopt)
  File "/usr/local/lib/python2.7/dist-packages/bypy/bypy.py", line 425, in __init__
    cached.loadcache()
  File "/usr/local/lib/python2.7/dist-packages/bypy/cached.py", line 201, in loadcache
    perr("Fail to load the Hash Cache, no caching.\n{}".format(formatex(ex)))
  File "/usr/local/lib/python2.7/dist-packages/bypy/util.py", line 73, in formatex
    type(ex), ex, ''.join(traceback.format_stack()))

/apps/bypy ($t $f $s $m $d):
D Audiobooks 0 2018-03-20, 13:34:23 

```

**Comment by d3banjan** [comment]
Related to #228 ?? In that case this is not a fatal error?

**Comment by houtianze** [comment]
Thanks for the feedback.

- Yes, your 2nd comment seems about the same error as in #228 , so yes, the error is not fatal, you can ignore it, just that there won't be any caching for hash calculation during upload/download.
 
- The `UnicodeDecodeError` is a bit strange, as I've never heard people having this problem loading/saving hash cache. Maybe your system encoding is not `UTF-8`? I suspect it's related to system locale configurations / garbled file names.

- You can inspect `~/.bypy/bypy.hashcache.json` to see why it failed to load/save, and you can safely delete it to get rid of the problem. However, if the problem re-occurs after you run `bypy` again, then I think you need to check system locale/file names for root cause.

- To make sure cache saving/loading errors won't affect normal operations, I've updated the package, please run `pip install -U bypy` to update to the latest version. The latest version (1.6.1) won't abort due to cache loading/saving errors.
