### ISSUE TITLE
请问 <type 'exceptions.KeyError'> - u'md5' 是什么错误?

### ISSUE THREAD

**Issue by GreenEric** [houtianze/bypy#484]
请问这是什么问题? 应该要怎么调整?

eric@eric:~/bin$ bypy -v syncup /home/ericoffice/WORK /WORK2
Loading Hash Cache File '/home/eric/.bypy/bypy.hashcache.json'...
Hash Cache File loaded.
Gathering local directory ...
Done
Gathering remote directory ...
<E> [23:04:03] Exception occurred:
Exception:
<type 'exceptions.KeyError'> - u'md5'
Stack:
  File "/home/eric/.local/bin/bypy", line 11, in <module>
    sys.exit(main())
  File "/home/eric/.local/lib/python2.7/site-packages/bypy/bypy.py", line 3700, in main
    perr("Exception occurred:\n{}".format(formatex(ex)))
  File "/home/eric/.local/lib/python2.7/site-packages/bypy/util.py", line 73, in formatex
    type(ex), ex, ''.join(traceback.format_stack()))

**Comment by bg4uvr** [comment]
这两天一直是这个问题，不能用了。而且在i386下和arm下问题都一样。不知道到底是百度那边有什么变化，还是软件的问题。请作者或了解的朋友指导一下，感谢🙏

**Comment by higoodboys** [comment]
现在我也是这个错误，希望作者有时间看下，谢谢

**Comment by bg4uvr** [comment]
<D> Full URL: https://pcs.baidu.com/rest/2.0/pcs/file?access_token= ****
<D> HTTP Status Code: 200
<D> 200 OK, processing action
<D> Request OK
<E> [09:38:04] Exception occurred:
Exception:
<type 'exceptions.KeyError'> - u'md5'
Stack:
  File "/usr/local/bin/bypy", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/bypy/bypy.py", line 3700, in main
    perr("Exception occurred:\n{}".format(formatex(ex)))
  File "/usr/local/lib/python2.7/dist-packages/bypy/util.py", line 73, in formatex
    type(ex), ex, ''.join(traceback.format_stack()))

Abort
Skip saving Hash Cache since it has not been updated.

**Comment by houtianze** [comment]
谢谢反馈。
已经在Python 2.7上重现，等下看看什么原因再修正。

【临时解决方案】：在python**3**下安装貌似没这个问题：
```
pip2 uninstall bypy
pip3 install bypy
```
(可能需要sudo）

**Comment by higoodboys** [comment]
我是python3也是有这个问题呢，谢谢作者关注

Hou Tianze <notifications@github.com>于2019年5月18日 周六12:59写道：

**Comment by houtianze** [comment]
@higoodboys 那听起来像是break了，我看看。

**Comment by higoodboys** [comment]
谢谢，大概看了下是__request_work里r = self.__requester.request(method, url, params =
parsnew, timeout = self.__timeout, verify = self.__checkssl, **kwargs)
里发生异常了，麻烦作者看下


Hou Tianze <notifications@github.com>于2019年5月18日 周六13:15写道：

**Comment by bg4uvr** [comment]
经测试，python3下问题相同。

**Comment by houtianze** [comment]
找到原因了，已经上传了`1.6.5`，更新一下应该就可以解决问题了：
`pip install bypy`

原因：现在百度api返回的目录列表有时候会没有`md5`这个属性，原来代码没对这个做检查。

谢谢反馈和等待。

**Comment by bg4uvr** [comment]
感谢作者无私奉献与快速反馈~
