### ISSUE TITLE
认证失败

### ISSUE THREAD

**Issue by songhuili** [houtianze/bypy#510]
`bypy info
Please visit:
https://openapi.baidu.com/oauth/2.0/authorize?scope=basic+netdisk&response_type=code&redirect_uri=oob&client_id=q8W******************************
And authorize this app
Paste the Authorization Code here within 10 minutes.
Press [Enter] when you are done
12395cbca37*********************53942
Authorizing, please be patient, it may take upto 300 seconds...
Authorizing/refreshing with the OpenShift server ...
OpenShift server failed, authorizing/refreshing with the Heroku server ...
Heroku server failed, authorizing/refreshing with the Heroku1 server ...
Heroku1 server failed. Last resort: authorizing/refreshing with the GAE server ...
<E> [13:16:06] Fatal: All server authorizations failed.
<I> [13:16:06] ----------------------------------------------------------------
<I> [13:16:06] This is most likely caused by authorization errors.
Possible causes:
 - You didn't run this program for a long time (more than a month).
 - You changed your Baidu password after authorizing this program.
 - You didn't give this program the 'netdisk' access while authorizing.
 - ...
Possible fixes:
 1. Remove the authorization token by running with the parameter '-c', and then re-run this program.
 2. If (1) still doesn't solve the problem, you may have to go to:
    https://passport.baidu.com/accountbind
    and remove the authorization of this program, and then re-run this program.`

**Comment by songhuili** [comment]
今天认证失败 试了好几次了 睡能帮我解决一下 谢谢

**Comment by btrspg** [comment]
同样也开始认证失败

**Comment by yukiloh** [comment]
Authorizing, please be patient, it may take upto 300 seconds...
Authorizing/refreshing with the OpenShift server ...
OpenShift server failed, authorizing/refreshing with the Heroku server ...
Heroku server failed, authorizing/refreshing with the Heroku1 server ...
Heroku1 server failed. Last resort: authorizing/refreshing with the GAE server ...
<E> [08:15:56] Fatal: All server authorizations failed.
<I> [08:15:56] ----------------------------------------------------------------
<I> [08:15:56] This is most likely caused by authorization errors.
Possible causes:
 - You didn't run this program for a long time (more than a month).
 - You changed your Baidu password after authorizing this program.
 - You didn't give this program the 'netdisk' access while authorizing.
 - ...
Possible fixes:
 1. Remove the authorization token by running with the parameter '-c', and then re-run this program.
 2. If (1) still doesn't solve the problem, you may have to go to:
    https://passport.baidu.com/accountbind
    and remove the authorization of this program, and then re-run this program.
as same as me

**Comment by houtianze** [comment]
不好意思，server被强制睡眠了，已修复。
谢谢反馈。

**Comment by XiongKexin** [comment]
我今天也出现了这样的问题，无论如何都认证不了，谁能帮忙解决一下吗？谢谢
