### ISSUE TITLE
你好，bypy授权一直显示失败，取消之后重新授权也不管用

### ISSUE THREAD

**Issue by XiongKexin** [houtianze/bypy#514]
报错显示如下：
......
And authorize this app
Paste the Authorization Code here within 10 minutes.
Press [Enter] when you are done
cedff5a74fb1f42d3c0e57
Authorizing, please be patient, it may take upto 300 seconds...
Authorizing/refreshing with the OpenShift server ...
OpenShift server failed, authorizing/refreshing with the Heroku server ...
Heroku server failed, authorizing/refreshing with the Heroku1 server ...
Heroku1 server failed. Last resort: authorizing/refreshing with the GAE server ...
<E> [17:51:43] Fatal: All server authorizations failed.
<I> [17:51:43] ----------------------------------------------------------------
<I> [17:51:43] This is most likely caused by authorization errors.
Possible causes:
 - You didn't run this program for a long time (more than a month).
 - You changed your Baidu password after authorizing this program.
 - You didn't give this program the 'netdisk' access while authorizing.
 - ...
Possible fixes:
 1. Remove the authorization token by running with the parameter '-c', and then re-run this program.
 2. If (1) still doesn't solve the problem, you may have to go to:
    https://passport.baidu.com/accountbind
    and remove the authorization of this program, and then re-run this program.

**Comment by XiongKexin** [comment]
你好，我今天刚刚开始使用bypy，但是一直认证失败，取消又重来已经很多回了......

**Comment by yuanmingchen** [comment]
俺也一样

**Comment by mouzhai** [comment]
无法完成授权，所有服务器全部认证失败，使用代理也一样

pi@raspberrypi:~ $ python -m bypy info
Please visit:
https://openapi.baidu.com/oauth/2.0/authorize?scope=basic+netdisk&redirect_uri=oob&response_type=code&client_id=q8WE4EpCsau1oS0MplgMKNBn
And authorize this app
Paste the Authorization Code here within 10 minutes.
Press [Enter] when you are done

Authorizing, please be patient, it may take upto 300 seconds...
Authorizing with the Heroku server ...
Heroku server failed, authorizing with the Heroku1 server ...
Heroku1 server failed, authorizing with the Vercel server ...
Vercel server failed. Last resort: authorizing with the GAE server ...
<E> [10:16:20] Fatal: All server authorizations failed.
<I> [10:16:20] ----------------------------------------------------------------
<I> [10:16:20] This is most likely caused by authorization errors.
Possible causes:
 - You didn't run this program for a long time (more than a month).
 - You changed your Baidu password after authorizing this program.
 - You didn't give this program the 'netdisk' access while authorizing.
 - ...
Possible fixes:
 1. Remove the authorization token by running with the parameter '-c', and then re-run this program.
 2. If (1) still doesn't solve the problem, you may have to go to:
    https://passport.baidu.com/accountbind
    and remove the authorization of this program, and then re-run this program.

**Comment by KaishuaiXu** [comment]
我也是，看之前回复，大部分服务器挂了？只有翻墙才能连最后一个GAE。

**Comment by houtianze** [comment]
最新版1.8应该已经彻底解决了授权问题。
