### ISSUE TITLE
关于百度网盘的新hash算法的一些看法和讨论

### ISSUE THREAD

**Issue by Jeffz615** [houtianze/bypy#575]
整体文件的hash算法可能已经[不是单纯的md5](https://www.zhihu.com/question/394178548)了，虽然不是很懂百度这么做的意义，如果有大佬能分析出来新的hash算法当然是更好的。
但是需要验证的话也许可以退而求其次验证文件切片的md5和文件大小是否一致？至少切片的hash还是md5

ps: 目前我将bypy用于自己的项目当中，只能 verify=False 来用了

**Comment by houtianze** [comment]
感谢提供信息。貌似已经有牛人分析出来算法了 #576 
我去验证一下，尽快merge。

**Comment by weynhamz** [comment]
The encrypt_hash fix is great, but Baidu's hash storage is messed up because of tech debt I believe, sometimes it returns unencrypted hash for some files (probably very old files). 

Here is a [quick/dirty fix](https://github.com/weynhamz/bypy/commit/23f750071544ddd1a411b7332b0258a279f0d8c7) that solved my problem, just for reference, it needs more refactoring to be fixed properly.

**Comment by houtianze** [comment]
@weynhamz Thanks for spotting this and the referencing fix 👍 

I try too see how to merge it properly when I get some time, I'm just a little bit concerned whether this will affect other parts of the program, but since you've tested that this works for you, I guess it should be safe to merge after some clean up.

**Comment by yqs112358** [comment]
```
<I> [09:10:40] Local and remote file hash DOESN'T match
```
这个问题有希望解决吗，目前只能使用verify=False才可以保证正常上传文件，而且即使设置了verify，md5不一致的时候调用upload的返回值仍然不为0，这使得很难判断上传是否真正成功

**Comment by houtianze** [comment]
@yqs112358 这个问题我搞不定，貌似是百度那边的哈希算法有改动，现在的fix是别人分析和分享出来的。

**Comment by Paper-Folding** [comment]
@houtianze 小文件这个 `encrypt_md5` 方法出来的结果和云端一致的，大文件就不对了，请问大大你知道大文件怎么算的吗？

**Comment by houtianze** [comment]
> @houtianze 小文件这个 `encrypt_md5` 方法出来的结果和云端一致的，大文件就不对了，请问大大你知道大文件怎么算的吗？

这个一直没搞明白，当初的算法也是当初提PR的牛人搞出来的。这个黑盒部分我搞不定。
