### ISSUE TITLE
授权问题

### ISSUE THREAD

**Issue by 6923403** [houtianze/bypy#589]
2021-10-21： 解决方案就是挂vpn
---
阿里云
 vpn也试过 不行

Authorizing, please be patient, it may take upto 300 seconds...
Authorizing with the Heroku server ...
Heroku server failed, authorizing with the Heroku1 server ...
Heroku1 server failed, authorizing with the Vercel server ...
Vercel server failed. Last resort: authorizing with the GAE server ...
<E> [22:48:09] Fatal: All server authorizations failed.
<I> [22:48:09] ----------------------------------------------------------------
<I> [22:48:09] This is most likely caused by authorization errors.
Possible causes:
 - You didn't run this program for a long time (more than a month).
 - You changed your Baidu password after authorizing this program.
 - You didn't give this program the 'netdisk' access while authorizing.
 - ...
Possible fixes:
 1. Remove the authorization token by running with the parameter '-c', and then re-run this program.
 2. If (1) still doesn't solve the problem, you may have to go to:
    https://passport.baidu.com/accountbind
    and remove the authorization of this program, and then re-run this program.

**Comment by 6923403** [comment]
尝试清除``.bypy`` 解除授权之后重试也失败了

**Comment by houtianze** [comment]
```bash
rm -Rf ~/.bypy
rm -f ~/.bypy.*
```

也不行？你在vps上能跑过这两个命令吗？
```bash
curl -L https://bypyoauth.herokuapp.com/
curl -L https://bypyoauth1.herokuapp.com/
```

**Comment by duchenpaul** [comment]
> ```shell
> ```shell
> curl -L https://bypyoauth1.herokuapp.com/
> ```
> 
> 
>     
>       
>     
> 
>       
>     
> 
>     
>   
>       
> ```

@houtianze  不行, 似乎已经被墙, 请提供搭建bypyoauth的方法, 以及让bypy关联自建认证服务器的方法.
准备自建服务器, 不用heroku

**Comment by duchenpaul** [comment]
全局翻墙后可以认证, 确认是heroku被党妈屏蔽了. 建议增加自定义地址传入选项.
服务器定义在[这里](https://sourcegraph.com/search?q=context:global+repo:%5Egithub%5C.com/houtianze/bypy%24+hero&patternType=literal)

**Comment by duchenpaul** [comment]
另: 似乎认证服务器只有Heroku1 一台能用了....

**Comment by duchenpaul** [comment]
确定可以全局翻墙? 
```
curl www.google.com
```

**Comment by duchenpaul** [comment]
我大概摸清了怎么自建服务器 但是实在不想百度实名认证来获取什么开发者api

**Comment by 6923403** [comment]
> 确定可以全局翻墙?
> 
> ```
> curl www.google.com
> ```

iZuf6grc3diwebhwb6r3qcZ:~ # curl cip.cc            
IP      : 18.163.99.154
地址    : 美国  马萨诸塞州  剑桥
运营商  : mit.edu

数据二  : 香港 | Amazon数据中心

数据三  : 美国 | 亚马逊

**Comment by 6923403** [comment]
> 这个返回啥?
> 
> ```shell
> chend@dev-dops-chend-test ~ $ curl -L https://bypyoauth1.herokuapp.com/
> bypyoauth
> Updated: Sat Oct 16 13:43:01 2021
> ```
> 
> 如果跟我返回的一样, 那就可以, 执行 `bypy info -vd`来登录, 理论上就可以登上, 我也是在路由器端开了全局, 然后秒登上

 curl -L https://bypyoauth1.herokuapp.com/
bypyoauth
Updated: Sat Oct 16 13:43:01 2021

不行 我还是秒失败  我是阿里云

**Comment by 6923403** [comment]
> > 这个返回啥?
> > ```shell
> > chend@dev-dops-chend-test ~ $ curl -L https://bypyoauth1.herokuapp.com/
> > bypyoauth
> > Updated: Sat Oct 16 13:43:01 2021
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 如果跟我返回的一样, 那就可以, 执行 `bypy info -vd`来登录, 理论上就可以登上, 我也是在路由器端开了全局, 然后秒登上
> 
> iZuf6grc3diwebhwb6r3qcZ:~ # curl -L https://bypyoauth1.herokuapp.com/ bypyoauth Updated: Sat Oct 16 13:43:01 2021
> 
> 不行 我还是秒失败 我是阿里云

那这个看来是我的问题了 我在本地测试了下 授权成功了。。

**Comment by bg4uvr** [comment]
确认是认证服务器被墙的原因，使用蓝灯局域网代理，认证秒成功。

**Comment by 2010dainifei** [comment]
能否给个教程我们来试一下。。。。。。centos系统。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "houtianze/bypy"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月2日(星期二) 下午3:14
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [houtianze/bypy] 授权问题 (#589)





 
确认是认证服务器被墙的原因，使用蓝灯局域网代理，认证秒成功。
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by bg4uvr** [comment]
> 能否给个教程我们来试一下。。。。。。centos系统。
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "houtianze/bypy" ***@***.***&gt;; 发送时间:&nbsp;2021年11月2日(星期二) 下午3:14 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [houtianze/bypy] 授权问题 (#589) 确认是认证服务器被墙的原因，使用蓝灯局域网代理，认证秒成功。 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

修改蓝灯目录下的 settings.yaml 文件，addr和socksAddr字段更改为你电脑的局域网IP地址，然后centos设置代理即可（具体方法自行搜索）。

**Comment by 2010dainifei** [comment]
谢谢，今晚我试试。另外，我正在尝试搭建百度的认证服务器，一直认证失败。希望作者能协助一下搭建认证，若能成功，我可以把这些服务器公布给大家一起使用。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "houtianze/bypy"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月2日(星期二) 下午4:38
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [houtianze/bypy] 授权问题 (#589)





  
能否给个教程我们来试一下。。。。。。centos系统。
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "houtianze/bypy" @.&gt;; 发送时间:&nbsp;2021年11月2日(星期二) 下午3:14 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [houtianze/bypy] 授权问题 (#589) 确认是认证服务器被墙的原因，使用蓝灯局域网代理，认证秒成功。 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.
  
修改蓝灯目录下的 settings.yaml 文件，addr和socksAddr字段更改为你电脑的局域网IP地址，然后centos设置代理即可（具体方法自行搜索）。
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by HanweiWu** [comment]
借鉴各位大佬的讲解, 我用代理的方案成功授权, 但服务器配置代理软件有些困难, 我分享一波我的解决方案:
  -> 本地电脑代理 + 蒲公英全穿透 + 服务器配置export all_proxy=[蒲公英穿透本地ip]:[本地代理端口]
本机电脑代理很简单, 相信各位大佬都用过各种破解软件, 关键使用蒲公英全端口穿透连通服务器, 让服务器走本地电脑小软件的代理

**Comment by houtianze** [comment]
刚刚发布了最新版1.7.4，令牌授权和刷新的问题这次应该是比较彻底的解决了，可以升级试一试：
`pip install -U bypy`

这次更新只留了两个我测试过没被墙的授权服务器，并且修正了令牌刷新逻辑，应该授权这块儿是不会有太大问题了。

**Comment by AbelDengGang** [comment]
我最新的1.7.6上是这样的: 
我用的是国外的服务器,应该不会有墙的问题.
Paste the Authorization Code here within 10 minutes.
Press [Enter] when you are done
xxxxxxxxxxxxx
Authorizing, please be patient, it may take upto 300 seconds...
Authorizing with the Vercel server ...
Successfully authorized
Refreshing, please be patient, it may take upto 300 seconds...
Refreshing with the Vercel server ...
Token successfully refreshed
Refreshing, please be patient, it may take upto 300 seconds...
Refreshing with the Vercel server ...
Token successfully refreshed
Refreshing, please be patient, it may take upto 300 seconds...
Refreshing with the Vercel server ...
Token successfully refreshed
Refreshing, please be patient, it may take upto 300 seconds...
Refreshing with the Vercel server ...
Token successfully refreshed
Refreshing, please be patient, it may take upto 300 seconds...
Refreshing with the Vercel server ...
Token successfully refreshed

**Comment by houtianze** [comment]
@AbelDengGang 
谢谢反馈。你是运行什么命令时出现这种错误的？能加个`-dv`参数再跑一下吗？看起来授权后一直在刷新令牌，不知道为啥会这样？

**Comment by houtianze** [comment]
最新版1.8彻底解决授权问题。
